version: '3'

services:
  bigtop_hostname0:
    container_name: bigtop_hostname0
    command: /sbin/init
    domainname: bigtop.apache.org
    image: bigtop/puppet:trunk-rockylinux-8
    mem_limit: 8g
    mem_swappiness: 0
    ports:
      - "8080:8080"
    privileged: true
    volumes:
      - ./var/www/html/ambari_repo/ambari-3.0:/var/repo/ambari
      - ./conf/hosts:/etc/hosts
    networks:
      bigtop-network:
        ipv4_address: 172.20.0.2

  bigtop_hostname1:
    container_name: bigtop_hostname1
    command: /sbin/init
    domainname: bigtop.apache.org
    image: bigtop/puppet:trunk-rockylinux-8
    mem_limit: 8g
    mem_swappiness: 0
    privileged: true
    volumes:
      - ./var/www/html/ambari_repo/ambari-3.0:/var/repo/ambari
      - ./conf/hosts:/etc/hosts
    networks:
      bigtop-network:
        ipv4_address: 172.20.0.3

  bigtop_hostname2:
    container_name: bigtop_hostname2
    command: /sbin/init
    domainname: bigtop.apache.org
    image: bigtop/puppet:trunk-rockylinux-8
    mem_limit: 8g
    mem_swappiness: 0
    privileged: true
    volumes:
      - ./var/www/html/ambari_repo/ambari-3.0:/var/repo/ambari
      - ./conf/hosts:/etc/hosts
    networks:
      bigtop-network:
        ipv4_address: 172.20.0.4

  bigtop_hostname3:
    container_name: bigtop_hostname3
    command: /sbin/init
    domainname: bigtop.apache.org
    image: bigtop/puppet:trunk-rockylinux-8
    mem_limit: 8g
    mem_swappiness: 0
    privileged: true
    volumes:
      - ./var/www/html/ambari_repo/ambari-3.0:/var/repo/ambari
      - ./conf/hosts:/etc/hosts
    networks:
      bigtop-network:
        ipv4_address: 172.20.0.5

networks:
  bigtop-network:
    external: true
    name: bigtop-network